"""
LangGraph agent for MentorML.

A Plan-and-Execute agent (CoT + ReAct) that:
1. PLAN: Decomposes learning queries into teaching steps (Chain-of-Thought)
2. EXECUTE: Carries out each step with tool-based diagram retrieval (ReAct)
3. REFLECT: Checks completeness and iterates if needed

Maintains conversation state via Redis checkpointing.
"""

import json
from typing import TYPE_CHECKING, Annotated, Literal

from langchain_core.messages import AIMessage, BaseMessage, HumanMessage, SystemMessage, ToolMessage
from langchain_google_genai import ChatGoogleGenerativeAI
from langgraph.checkpoint.base import BaseCheckpointSaver
from langgraph.checkpoint.memory import InMemorySaver
from langgraph.graph import END, START, StateGraph
from langgraph.graph.message import add_messages
from langgraph.prebuilt import ToolNode
from pydantic import BaseModel, Field

from agent.tools import create_retrieval_tool

if TYPE_CHECKING:
    from model.scorer import SigLIPScorer


# --- State Schema ---

class TeachingPlan(BaseModel):
    """Structured teaching plan generated by CoT reasoning."""
    topic: str = Field(description="The main topic being taught")
    steps: list[str] = Field(description="Ordered list of teaching steps")
    diagrams_needed: list[str] = Field(description="Concepts that would benefit from visual diagrams")


class AgentState(BaseModel):
    """State for the Plan-and-Execute teaching agent."""
    messages: Annotated[list[BaseMessage], add_messages]
    plan: TeachingPlan | None = None
    
    class Config:
        arbitrary_types_allowed = True


# --- Prompts ---

PLANNER_PROMPT = """You are a teaching planner for AI/ML concepts.

Given a user's question, create a structured teaching plan that breaks down the explanation
into clear, progressive steps. Consider what visual diagrams would help.

You have access to diagrams from Jay Alammar's "Illustrated" posts covering:
- Transformers and Attention
- BERT, GPT-2, GPT-3
- Word2Vec, embeddings
- Stable Diffusion

Output your plan as JSON with this structure:
{
    "topic": "main topic",
    "steps": ["step 1", "step 2", ...],
    "diagrams_needed": ["concept that needs diagram", ...]
}

Keep plans concise (2-4 steps for simple questions, up to 6 for complex topics).
"""

EXECUTOR_PROMPT = """You are MentorML, an expert AI/ML teaching assistant that uses visual diagrams to enhance learning.

Provide a clear, complete explanation of the topic. Use the retrieve_diagram tool to find 
1-2 relevant visuals (no more than 2 per response). Quality over quantity - pick the most 
impactful diagrams rather than retrieving many.

IMPORTANT: Only reference diagrams you have ACTUALLY retrieved using the tool. 
Do NOT make up or assume diagram IDs. When you successfully retrieve a diagram, 
reference it naturally using the format: [diagram: diagram_XXX] where XXX is the 
exact ID returned by the tool.

DIAGRAM FORMATTING: Always place diagram references on their own line, with a blank line 
before and after. Then describe what the diagram shows AFTER it. Never write "As you see in 
[diagram: ...]" or reference diagrams inline. Instead:

CORRECT:
Here's how attention works:

[diagram: diagram_042]

The diagram above illustrates the scaled dot-product attention mechanism...

WRONG:
As you see in [diagram: diagram_042], it shows the attention mechanism...

Write your response as a standalone explanation - avoid "wrap-up" phrases like 
"let's bring it all together" or "in conclusion" since this is a single response.

Be friendly, use analogies, and make concepts accessible.
"""


# --- Node Functions ---

def plan_node(state: AgentState) -> dict:
    """
    CoT Planning: Decompose the user's question into teaching steps.
    Only plans on the first message or when there's a new question.
    """
    # Get the last human message
    last_human_msg = None
    for msg in reversed(state.messages):
        if isinstance(msg, HumanMessage):
            last_human_msg = msg.content
            break
    
    if not last_human_msg:
        return {}
    
    # Check if this is a follow-up or new topic
    # For follow-ups in an existing conversation, skip heavy re-planning
    if state.plan is not None and len(state.messages) > 2:
        # Lightweight check: is this a follow-up or new topic?
        llm = ChatGoogleGenerativeAI(model="gemini-3-flash-preview", temperature=0, thinking_level="low")
        check = llm.invoke([
            SystemMessage(content="Is this a follow-up question about the same topic, or a new topic? Reply only: FOLLOWUP or NEW"),
            HumanMessage(content=f"Previous topic: {state.plan.topic}\nNew message: {last_human_msg}")
        ])
        # Use .text for Gemini 3+ which returns content as list of blocks
        check_text = getattr(check, 'text', None) or (
            check.content if isinstance(check.content, str) else str(check.content)
        )
        if "FOLLOWUP" in check_text.upper():
            # For follow-ups, create a minimal plan
            return {
                "plan": TeachingPlan(
                    topic=state.plan.topic,
                    steps=[f"Address follow-up: {last_human_msg}"],
                    diagrams_needed=[]
                ),
                "current_step": 0,
                "steps_completed": [],
            }
    
    # Full planning for new topics
    llm = ChatGoogleGenerativeAI(model="gemini-3-flash-preview", temperature=0.3, thinking_level="low")
    response = llm.invoke([
        SystemMessage(content=PLANNER_PROMPT),
        HumanMessage(content=last_human_msg)
    ])
    
    # Parse the plan
    try:
        # Use .text for Gemini 3+ which returns content as list of blocks
        content = getattr(response, 'text', None) or (
            response.content if isinstance(response.content, str) else str(response.content)
        )
        if "```json" in content:
            content = content.split("```json")[1].split("```")[0]
        elif "```" in content:
            content = content.split("```")[1].split("```")[0]
        
        plan_data = json.loads(content.strip())
        plan = TeachingPlan(**plan_data)
    except (json.JSONDecodeError, KeyError, TypeError, IndexError):
        # Fallback: simple single-step plan
        topic_text = last_human_msg if isinstance(last_human_msg, str) else str(last_human_msg)
        plan = TeachingPlan(
            topic=topic_text[:50],
            steps=[f"Explain: {last_human_msg}"],
            diagrams_needed=["relevant concept"]
        )
    
    return {
        "plan": plan,
        "current_step": 0,
        "steps_completed": [],
    }


def _make_execute_node(tools: list):
    """Factory to create execute node with tools bound."""
    def execute_node(state: AgentState) -> dict:
        """
        ReAct Execution: Generate a comprehensive response using the teaching plan.
        Single pass - uses plan for structure, can call tools for diagrams.
        """
        if not state.plan:
            return {"messages": [AIMessage(content="I'd be happy to help! What would you like to learn about?")]}
        
        plan = state.plan
        
        # Build the execution prompt with full plan context
        context = f"""
You have created this teaching plan - use it to structure your response:

Topic: "{plan.topic}"
Steps to cover:
{chr(10).join(f"  {i+1}. {s}" for i, s in enumerate(plan.steps))}

Diagrams that would help: {", ".join(plan.diagrams_needed) if plan.diagrams_needed else "none identified"}

Generate a single, comprehensive explanation that covers all the steps above.
Use the retrieve_diagram tool if a visual would help explain a concept.
"""
        
        # Create LLM with tools bound
        llm = ChatGoogleGenerativeAI(model="gemini-3-flash-preview", temperature=0.3, thinking_level="low")
        llm_with_tools = llm.bind_tools(tools)
        
        # Build proper message sequence for Gemini
        user_messages = [m for m in state.messages if isinstance(m, HumanMessage)]
        
        messages_for_llm: list[BaseMessage] = [
            SystemMessage(content=EXECUTOR_PROMPT + "\n\n" + context),
        ]
        
        # Add the user question
        if user_messages:
            messages_for_llm.append(user_messages[-1])
        
        # Handle tool call/response pairs for ReAct loop
        recent_tool_messages = [m for m in state.messages[-4:] if isinstance(m, ToolMessage)]
        if recent_tool_messages:
            for m in reversed(state.messages):
                if isinstance(m, AIMessage) and getattr(m, "tool_calls", None):
                    messages_for_llm.append(m)
                    break
            messages_for_llm.extend(recent_tool_messages)
        
        response = llm_with_tools.invoke(messages_for_llm)
        
        return {"messages": [response]}
    
    return execute_node


def should_use_tools(state: AgentState) -> Literal["tools", "end"]:
    """Check if the last message has tool calls."""
    last_message = state.messages[-1] if state.messages else None
    if last_message:
        tool_calls = getattr(last_message, "tool_calls", None)
        if tool_calls:
            return "tools"
    return "end"


# --- Graph Construction ---

def create_agent(
    scorer: "SigLIPScorer", 
    checkpointer: BaseCheckpointSaver | None = None,
    enable_vision: bool = True,
):
    """
    Create a Plan-and-Execute LangGraph agent with CoT planning and ReAct execution.
    
    Flow: plan → execute ⇄ tools → end
    
    Args:
        scorer: Pre-initialized SigLIPScorer instance
        checkpointer: Optional checkpoint saver for conversation state.
                     If None, uses InMemorySaver (state lost on restart).
        enable_vision: Whether to enable vision review for retrieved diagrams.
                      Adds ~5-10s latency but provides contextual descriptions.
        
    Returns:
        Compiled LangGraph agent
    """
    # Use in-memory saver if no checkpointer provided
    if checkpointer is None:
        checkpointer = InMemorySaver()
    
    # Create retrieval tool
    retrieval_tool = create_retrieval_tool(scorer, enable_vision=enable_vision)
    tools = [retrieval_tool]
    
    # Create tool node
    tool_node = ToolNode(tools)
    
    # Create execute node with tools bound
    execute_node = _make_execute_node(tools)
    
    # Build the graph (simplified: plan once, execute once with tool loop)
    workflow = StateGraph(AgentState)
    
    # Add nodes
    workflow.add_node("plan", plan_node)
    workflow.add_node("execute", execute_node)
    workflow.add_node("tools", tool_node)
    
    # Add edges: plan → execute ⇄ tools → end
    workflow.add_edge(START, "plan")
    workflow.add_edge("plan", "execute")
    workflow.add_conditional_edges("execute", should_use_tools, {"tools": "tools", "end": END})
    workflow.add_edge("tools", "execute")  # After tool use, continue execution
    
    # Compile with checkpointer
    agent = workflow.compile(checkpointer=checkpointer)
    
    return agent


def get_agent():
    """Get the initialized agent. Raises if not created."""
    raise RuntimeError("Use create_agent() to create an agent instance.")
